"""lectors1

Revision ID: 510fe9b0dd02
Revises: 35dacaf83eb0
Create Date: 2025-09-12 08:09:49.045538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510fe9b0dd02'
down_revision: Union[str, Sequence[str], None] = '35dacaf83eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_lectors', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('course_lectors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('course_lectors_c_id_fkey'), 'course_lectors', type_='foreignkey')
    op.drop_constraint(op.f('course_lectors_u_id_fkey'), 'course_lectors', type_='foreignkey')
    op.create_foreign_key(None, 'course_lectors', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'course_lectors', 'users', ['user_id'], ['id'])
    op.drop_column('course_lectors', 'u_id')
    op.drop_column('course_lectors', 'c_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_lectors', sa.Column('c_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('course_lectors', sa.Column('u_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_lectors', type_='foreignkey')
    op.drop_constraint(None, 'course_lectors', type_='foreignkey')
    op.create_foreign_key(op.f('course_lectors_u_id_fkey'), 'course_lectors', 'users', ['u_id'], ['id'])
    op.create_foreign_key(op.f('course_lectors_c_id_fkey'), 'course_lectors', 'course', ['c_id'], ['id'])
    op.drop_column('course_lectors', 'user_id')
    op.drop_column('course_lectors', 'course_id')
    # ### end Alembic commands ###
